# Generated by Django 2.0.2 on 2018-09-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
    ]
