# Generated by Django 2.0.2 on 2018-09-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20180909_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='status',
            field=models.ForeignKey(blank=True, default='Por Realizar', null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.Status'),
        ),
    ]
