# Generated by Django 2.0.2 on 2018-09-09 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_auto_20180909_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.Status'),
        ),
    ]
