# Generated by Django 2.0.2 on 2018-09-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20180909_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
