# Generated by Django 2.0.2 on 2019-02-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_iglesia_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la galeria')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('actividad', models.ManyToManyField(to='actividades.Actividades')),
            ],
        ),
    ]
