# Generated by Django 2.0.2 on 2019-02-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='actividad',
        ),
        migrations.AddField(
            model_name='album',
            name='actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividades'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='album',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='album',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre del Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='imagen',
            field=models.ManyToManyField(to='actividades.Imagen'),
        ),
    ]
