# Generated by Django 2.0.2 on 2019-02-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_auto_20190213_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='images', verbose_name='Imagen'),
        ),
    ]
