# Generated by Django 2.0.2 on 2019-02-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_auto_20190213_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imagen',
        ),
        migrations.AddField(
            model_name='album',
            name='imagen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.Photo'),
            preserve_default=False,
        ),
    ]
