# Generated by Django 2.0.2 on 2019-02-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_auto_20190214_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imagen',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.Album'),
            preserve_default=False,
        ),
    ]
