# Generated by Django 2.0.2 on 2018-10-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180901_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_iglesia',
            field=models.BooleanField(default=False, verbose_name='Iglesia'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_programador',
            field=models.BooleanField(default=False, verbose_name='Programador'),
        ),
    ]
