# Generated by Django 2.0.2 on 2019-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estatus',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
