# Generated by Django 2.0.2 on 2019-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='contenido',
            field=models.CharField(max_length=150, verbose_name='Contenido de la notificacion'),
        ),
    ]
