# Generated by Django 2.0.2 on 2019-02-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190214_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='estatus',
            field=models.CharField(default='No leida', max_length=20),
        ),
    ]
