# Generated by Django 2.0.2 on 2019-02-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190214_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.URLField(default=1, verbose_name='link a redireccionar'),
            preserve_default=False,
        ),
    ]
