# Generated by Django 2.0.2 on 2019-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notificacion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.URLField(null=True, verbose_name='link a redireccionar'),
        ),
    ]
