# Generated by Django 2.0.2 on 2019-04-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=9, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('roles', models.CharField(choices=[('Miembro', 'Miembro'), ('Lider', 'Lider'), ('Asistente', 'Asistente')], max_length=50)),
            ],
        ),
    ]
