# Generated by Django 2.0.2 on 2018-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Miembro'), (2, 'Lider'), (3, 'Asistente')]),
        ),
    ]
