# Generated by Django 2.0.2 on 2018-09-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20180902_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='roles',
            field=models.CharField(choices=[('Miembro', 'Miembro'), ('Lider', 'Lider'), ('Asistente', 'Asistente')], max_length=50),
        ),
    ]
