# Generated by Django 2.0.2 on 2019-04-09 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=60, verbose_name='Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diezmos.Concepto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('numero_trans', models.IntegerField(blank=True, null=True, verbose_name='Numero de Transferencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopago', models.CharField(max_length=60, verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diezmos.TipoDePago'),
        ),
    ]
