# Generated by Django 2.0.2 on 2018-09-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0006_auto_20180902_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('numero_trans', models.IntegerField(verbose_name='Numero de Transferencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopago', models.CharField(max_length=60, verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diezmos.TipoDePago'),
        ),
    ]
